### ISSUE TITLE
build failure on Ubuntu / ppc64el

### ISSUE THREAD

**Issue by LocutusOfBorg** [threez/ruby-vmstat#15]
Hi, seems that this package fails to detect the Vmstat:Memory on ppc64el
https://launchpadlibrarian.net/284514946/buildlog_ubuntu-yakkety-ppc64el.ruby-vmstat_2.2.0-2_BUILDING.txt.gz

```

Vmstat::Cpu
  Vmstat#cpu
    should return an array of ethernet information
    first cpu
      should return a vmstat cpu object
      methods
        should respond to #user
        should respond to #idle
        should respond to #system
        should respond to #nice
      content
        nice
          should be a kind of Numeric
        idle
          should be a kind of Numeric
        system
          should be a kind of Numeric
        user
          should be a kind of Numeric

Vmstat::Task
  Vmstat#task
    should be a vmstat task object
    content
      resident_size
        should be a kind of Numeric
      user_time_ms
        should be a kind of Numeric
      virtual_size
        should be a kind of Numeric
      system_time_ms
        should be a kind of Numeric
    methods
      should respond to #resident_size
      should respond to #system_time_ms
      should respond to #user_time_ms
      should respond to #virtual_size

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Vmstat Vmstat#filter_devices should filter ethernet devices
     # Temporarily skipped with xit
     # ./spec/vmstat_spec.rb:19

Failures:

  1) Vmstat::Solaris#memory should == #<struct Vmstat::Memory pagesize=4096, wired=409145, active=9018, inactive=0, free=61103, pageins=0, pageouts=0>
     Failure/Error: should == Vmstat::Memory.new(4096, 409145, 9018, 0, 61103, 0, 0)

       expected: #<struct Vmstat::Memory pagesize=4096, wired=409145, active=9018, inactive=0, free=61103, pageins=0, pageouts=0>
            got: #<struct Vmstat::Memory pagesize=65536, wired=409145, active=9018, inactive=0, free=61103, pageins=0, pageouts=0> (using ==)
       Diff:
       @@ -1,2 +1,2 @@
       -"#<struct Vmstat::Memory pagesize=4096, wired=409145, active=9018, inactive=0, free=61103, pageins=0, pageouts=0>"
       +"#<struct Vmstat::Memory pagesize=65536, wired=409145, active=9018, inactive=0, free=61103, pageins=0, pageouts=0>"
     # ./spec/vmstat/solaris_spec.rb:253:in `block (3 levels) in <top (required)>'

  2) Vmstat::ProcFS#task should == #<struct Vmstat::Task virtual_size=4807, resident_size=515, user_time_ms=2000, system_time_ms=0>
     Failure/Error: it { should == Vmstat::Task.new(4807, 515, 2000, 0) }

       expected: #<struct Vmstat::Task virtual_size=4807, resident_size=515, user_time_ms=2000, system_time_ms=0>
            got: #<struct Vmstat::Task virtual_size=300, resident_size=515, user_time_ms=2000, system_time_ms=0> (using ==)
       Diff:
       @@ -1,2 +1,2 @@
       -"#<struct Vmstat::Task virtual_size=4807, resident_size=515, user_time_ms=2000, system_time_ms=0>"
       +"#<struct Vmstat::Task virtual_size=300, resident_size=515, user_time_ms=2000, system_time_ms=0>"
     # ./spec/vmstat/procfs_spec.rb:70:in `block (3 levels) in <top (required)>'

  3) Vmstat::ProcFS#memory should have the right total
     Failure/Error:
       (subject.wired_bytes + subject.active_bytes + 
        subject.inactive_bytes + subject.free_bytes).should == 507344 * 1024

       expected: 519520256
            got: 519503872 (using ==)
     # ./spec/vmstat/procfs_spec.rb:39:in `block (3 levels) in <top (required)>'

  4) Vmstat::ProcFS#memory should == #<struct Vmstat::Memory pagesize=4096, wired=4906, active=6508, inactive=8405, free=107017, pageins=64599, pageouts=1104>
     Failure/Error: should == Vmstat::Memory.new(4096, 4906, 6508, 8405, 107017, 64599, 1104)

       expected: #<struct Vmstat::Memory pagesize=4096, wired=4906, active=6508, inactive=8405, free=107017, pageins=64599, pageouts=1104>
            got: #<struct Vmstat::Memory pagesize=65536, wired=308, active=406, inactive=525, free=6688, pageins=64599, pageouts=1104> (using ==)
       Diff:
       @@ -1,2 +1,2 @@
       -"#<struct Vmstat::Memory pagesize=4096, wired=4906, active=6508, inactive=8405, free=107017, pageins=64599, pageouts=1104>"
       +"#<struct Vmstat::Memory pagesize=65536, wired=308, active=406, inactive=525, free=6688, pageins=64599, pageouts=1104>"
     # ./spec/vmstat/procfs_spec.rb:34:in `block (3 levels) in <top (required)>'

Deprecation Warnings:

RSpec::Core::Configuration#treat_symbols_as_metadata_keys_with_true_values= is deprecated, it is now set to true as default and setting it to false has no effect.

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /<<PKGBUILDDIR>>/spec/vmstat_spec.rb:8:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

2 deprecation warnings total

Finished in 0.12744 seconds (files took 0.18087 seconds to load)
145 examples, 4 failures, 1 pending

Failed examples:

rspec ./spec/vmstat/solaris_spec.rb:252 # Vmstat::Solaris#memory should == #<struct Vmstat::Memory pagesize=4096, wired=409145, active=9018, inactive=0, free=61103, pageins=0, pageouts=0>
rspec ./spec/vmstat/procfs_spec.rb:70 # Vmstat::ProcFS#task should == #<struct Vmstat::Task virtual_size=4807, resident_size=515, user_time_ms=2000, system_time_ms=0>
rspec ./spec/vmstat/procfs_spec.rb:37 # Vmstat::ProcFS#memory should have the right total
rspec ./spec/vmstat/procfs_spec.rb:33 # Vmstat::ProcFS#memory should == #<struct Vmstat::Memory pagesize=4096, wired=4906, active=6508, inactive=8405, free=107017, pageins=64599, pageouts=1104>

Randomized with seed 17733

/usr/bin/ruby2.3 /usr/bin/rspec --pattern ./spec/\*\*/\*_spec.rb --format documentation failed
ERROR: Test "ruby2.3" failed. Exiting.
dh_auto_install: dh_ruby --install /<<PKGBUILDDIR>>/debian/ruby-vmstat returned exit code 1
debian/rules:6: recipe for target 'binary-arch' failed
make: *** [binary-arch] Error 1
dpkg-buildpackage: error: fakeroot debian/rules binary-arch gave error exit status 2
```

do you have any clue?

**Comment by threez** [comment]
Can you tell me the pagesize of your system?

**Comment by LocutusOfBorg** [comment]
@threez on ppc64el systems it is listed here
https://launchpadlibrarian.net/228062159/buildlog_ubuntu-xenial-ppc64el.procenv_0.43-2_BUILDING.txt.gz

If I read that log correctly:
```
  _SC_PAGESIZE: 65536
  _SC_PAGE_SIZE: 65536
```

**Comment by threez** [comment]
the test uses 4906 statically I think in the tests, that might be the reason for the failures

**Comment by LocutusOfBorg** [comment]
That was my wondering too, unfortunately I don't know how to fix, I'm not a ruby man :)
