### ISSUE TITLE
two tests failing on debian sid

### ISSUE THREAD

**Issue by pravi** [threez/ruby-vmstat#9]
I'm packaging vmstat for debian and found two test failing

```
**Failures:

  1) Vmstat::Disk Vmstat#disk content type should be a kind of Symbol
     Failure/Error: its(:type) { should be_a(Symbol) }
       expected nil to be a kind of Symbol
     # ./spec/vmstat/disk_spec.rb:43:in `block (4 levels) in <top (required)>'

  2) Vmstat performance it should behave like a not memory leaking method should not grow the memory in method boot_time more than 26% 
     Failure/Error: mem_after.should < (mem_before * (1 + percent / 100.0))

       expected: < 5751.9
            got:   6636
     Shared Example Group: "a not memory leaking method" called from ./spec/vmstat_spec.rb:43
     # ./spec/vmstat_spec.rb:35:in `block (4 levels) in <top (required)>'

**
```

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
$ rspec -v
3.4.3
```

**Comment by pravi** [comment]
I'd assume this is caused by rspec 3. Do you plan to support rspec 3?

**Comment by threez** [comment]
The second is unstable because it makes assumptions about the GC in ruby. The first i will look into.

**Comment by pravi** [comment]
@threez thanks! Can you make the second test optional or skip then?

**Comment by threez** [comment]
I can't quite explain the first error. Is your environment special? (In travis ci linux the tests are passing)
